import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MdcSelectModule, MdcDialogModule, MdcFabModule, MdcTabModule, MdcMenuModule, MdcCardModule, MdcIconModule, MdcListModule, MdcChipsModule, MdcRadioModule, MdcDrawerModule, MdcButtonModule, MdcSliderModule, MdcRippleModule, MdcSwitchModule, MdcTabBarModule, MdcCheckboxModule, MdcSnackbarModule, MdcImageListModule, MdcElevationModule, MdcFormFieldModule, MdcTypographyModule, MdcTextFieldModule, MdcTopAppBarModule, MdcLineRippleModule, MdcIconButtonModule, MdcMenuSurfaceModule, MdcTabScrollerModule, MdcTabIndicatorModule, MdcFloatingLabelModule, MdcLinearProgressModule, MdcNotchedOutlineModule } from '@angular-mdc/web';
@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MdcSelectModule,
    MdcDialogModule,
    MdcFabModule,
    MdcTabModule,
    MdcMenuModule,
    MdcCardModule,
    MdcIconModule,
    MdcListModule,
    MdcChipsModule,
    MdcRadioModule,
    MdcDrawerModule,
    MdcButtonModule,
    MdcSliderModule,
    MdcRippleModule,
    MdcSwitchModule,
    MdcTabBarModule,
    MdcCheckboxModule,
    MdcSnackbarModule,
    MdcImageListModule,
    MdcElevationModule,
    MdcFormFieldModule,
    MdcTypographyModule,
    MdcTextFieldModule,
    MdcTopAppBarModule,
    MdcLineRippleModule,
    MdcIconButtonModule,
    MdcMenuSurfaceModule,
    MdcTabScrollerModule,
    MdcTabIndicatorModule,
    MdcFloatingLabelModule,
    MdcLinearProgressModule,
    MdcNotchedOutlineModule
    
  ],
  exports: [
    MdcRippleModule,
    MdcSelectModule,
    MdcLineRippleModule,
    MdcNotchedOutlineModule,
    // MdcDialogModule,
    // MdcFabModule,
    // MdcTabModule,
    // MdcMenuModule,
    MdcCardModule,
    MdcIconModule,
    MdcListModule,
    // MdcChipsModule,
    // MdcRadioModule,
    // MdcDrawerModule,
    // MdcButtonModule,
    // MdcSliderModule,
    //
    // MdcSwitchModule,
    // MdcTabBarModule,
    // MdcCheckboxModule,
    // MdcSnackbarModule,
    // MdcImageListModule,
    MdcElevationModule,
    MdcFormFieldModule,
    MdcTypographyModule,
    MdcTextFieldModule,
    MdcTopAppBarModule,
    MdcIconButtonModule,
    MdcMenuSurfaceModule,
    // MdcTabScrollerModule,
    MdcTabIndicatorModule,
    MdcFloatingLabelModule,
    // MdcLinearProgressModule,

  ]
})
export class AmdcModule { }
